### ISSUE TITLE
AutoClose / Display of selected Items

### ISSUE THREAD

**Issue by unficyp** [bostrowski/APEX-Enhanced-Lov-Item#3]
Hi,
thanks for this great plugin !
2 Questions:
- when i unclick "multiple selection" - the end user is only allowd to make one selection. how can i force the lov to be closed automatically after selecting one value ?
- is it possible to "re-style" the selected items without any fancy css borders ?

Ok, 3rd question: When you you plan to implement supporting IG ? :P

Thanks !
Gerald

**Comment by bostrowski** [comment]
@unficyp 

> when i unclick "multiple selection" - the end user is only allowd to make one selection. how can i force the lov to be closed automatically after selecting one value ?

you should consider it as but which will be fixed in next week. Right now, I suggest using small hotfix to close prompt right after you select value.

1. Create dynamic action for event `change` (apex item or per class if you want to define it once on magic page 0)
2. Create true action `Execute JavaScript Code`
3. Insert JavaScript that will force the plugin instance to close prompt (code below)

`$(this.triggeringElement).trigger('click');`

If you are using click event for something else then let me know I will find other way :-)

> is it possible to "re-style" the selected items without any fancy css borders ?

You need to be more specific because I'm not sure what you want to do :-) In case of templating the results you can provide custom HTML template using plugin attributes - see demo application and help text built in the plugin

> Ok, 3rd question: When you you plan to implement supporting IG ? :P

To make the plugin compatibile with IG I will need some extra time. Right now, I'm focusing on implementing minor enhancments that are not yet available and will make plugin more flexible then it is right now. Of course I'm also focusing on fixing minor bugs. 

So the answer is: no sooner than middle of Q32019.

**Comment by bostrowski** [comment]
@unficyp 
I've released v1.0.3 which adds autoclose funcionality to singular selection. If you won't elaborate further about templating and IG I would like to close the thread.

Will wait for your answer till 5th of May.

**Comment by unficyp** [comment]
Oh, seems i missed you first reply...
thanks for the fix - will try it out tomorrow.
as for the other 2 points: 
CSS: i'm talking about restyling the result "tags" (.pretius--enhancedLovItem.mask .itemContainer > .itemContainerBody > div.tags > div.tag) - but i will try to use the custom html option or try to modify the css at page load.

IG: Q3/Q4 sound good !
Will close the issue :)
